### ISSUE TITLE
原方案在当module.exports为函数时的风险

### ISSUE THREAD

**Issue by benjycui** [saijs/seajs-sai#2]
当module.exports本身也是一个函数时，为了监控就要对其进行包装并替换原来的exports对像。但是由于整个exports对像都修改了，所以可能会存在较大的风险。

``` javascript
if (isFunction(exports)) {
  module.exports = function () {
    return catchError.call(this, moduleId, exports, arguments)
  };
}
```

**Comment by hotoo** [comment]
有以下几种情况：
1. define: isFunction(factory): 这是普通的函数，可以安全的包函数进行替换。
2. exec: isFunction(exports): 
   1. 如果是普通函数，可以进行安全的替换。
   2. 如果是构造函数，简单替换会影响对象类型，同时要考虑静态方法[3] 和原型方法[4]。严重风险。
3. exec: isFunction(exports.staticFunction): 如果是构造函数，同 [2.2]
4. exec: isFunction(exports.prototype.method): 
   1. 如果是普通函数，需要注意 this context.
   2. 如果是构造函数，同 [2.2]

结论：
1. 对于普通函数，可以进行包装替换。
2. 对于构造函数，则需要更为谨慎对待。

**Comment by benjycui** [comment]
sea.js 寿终了。
